fix(gh-actions): update Java to use temurin 17
music-encoding/docker-mei pull request #17
Opened 2023-06-06 10:14 UTC by musicEnfanthen

This PR updates the java version used in the docker image to temurin 17.

It also sorts the arguments a bit more alphabetically.

2023-06-06 10:15 UTC, musicEnfanthen commented
Tested locally, and build process seems to run fine.

2023-06-12 10:16 UTC, bwbohl approved these changes

2023-06-15 21:45 UTC, bwbohl requested changes

2023-06-15 21:45 UTC, bwbohl commented on Dockerfile
```suggestion

# Configure the Eclipse Adoptium apt repository
RUN apt-get update && \
    apt-get install -y wget apt-transport-https && \
    mkdir -p /etc/apt/keyrings && \
    wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc && \
    echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
```

2023-06-15 21:45 UTC, bwbohl commented on Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends apt-utils openjdk-${JAVA_VERSION}-jre-headless curl unzip git libc6 aptitude libaom-dev gdebi fonts-stix && \
```suggestion
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils temurin-${JAVA_VERSION}-jdk curl unzip git libc6 aptitude libaom-dev gdebi fonts-stix && \
```

2023-06-15 22:11 UTC, bwbohl approved these changes

2023-06-15 22:23 UTC, merged